language: nix
nix: 2.3.2

install:
  - nix-channel --update nixpkgs https://nixos.org/channels/nixos-19.09

  - nix-env -iA cachix -f https://cachix.org/api/v1/install

  - cachix use thought2

  - nix-build
